### ISSUE TITLE
okbuck can run in windows?

### ISSUE THREAD

**Issue by guhan121** [uber/okbuck#463] opened 2017-06-27 10:16 UTC
classpath 'com.android.tools.build:gradle:2.2.0'
        classpath 'com.uber:okbuck:0.22.1'

and 
      distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-all.zip

when i run "gradle tasks"
got

A problem occurred evaluating root project '360FloatWindowDemo'.
> Failed to apply plugin [id 'com.uber.okbuck']
   > Could not create an instance of type com.uber.okbuck.extension.LintExtension_Decorated.

Caused by: java.lang.NoSuchMethodError: org.gradle.api.artifacts.ResolvableDependencies.getArtifacts()Lorg/gradle/api/artifacts/ArtifactCollection;
        at com.uber.okbuck.core.util.ProjectUtil.findVersionInClasspath(ProjectUtil.java:70)
        at com.uber.okbuck.core.util.LintUtil.getDefaultLintVersion(LintUtil.java:32)
        at com.uber.okbuck.extension.LintExtension.<init>(LintExtension.java:28)
        at com.uber.okbuck.extension.LintExtension_Decorated.<init>(Unknown Source)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:42)

**Comment by guhan121** [comment] 2017-06-27 10:37
sorry , i do not restart android studio  ,so  gradle -version is 3.2

**Comment by guhan121** [comment] 2017-06-27 12:31
so  I use gradle 4.0 
when i run "gradle tasks"
Okbuck tasks
------------
buckWrapper - Create buck wrapper
okbuck - Okbuck task for the root project. Also sets up groovy and kotlin if required.
okbuckClean - Delete stale configuration files generated by OkBuck
setupOkbuck - Setup okbuck cache and dependencies

when i run "gradle okbuck"
* What went wrong:
Execution failed for task ':setupOkbuck'.
> Okbuck cannot be invoked without 'okbuck.wrapper' set to true. Use buckw instead

can run "gradle buckWrapper"
I can got buckw.

but it is a shell cmd.  okbuck cannot work in windows?

**Comment by kageiit** [comment] 2017-06-27 14:20
This is a good question. I am not sure how the dependency caches that are usually symlinks to files in gradle caches would work on windows.

We do not have windows support top of mind for okbuck, but I will however try to run okbuck's samples on a windows machine next week to see what bits do work

**Comment by kageiit** [comment] 2017-07-15 04:06
Closing as duplicate of #472

**Closed by kageiit** 2017-07-15 04:06 UTC
Labels: question
