### ISSUE TITLE
OkBuck is incompatible with Android Gradle Plugin 3.4.0+ (include 3.4.0)

### ISSUE THREAD

**Issue by leleliu008** [uber/okbuck#907] opened 2020-04-09 14:56 UTC
Android Gradle Plugin 3.4.0+ output:
```
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.api.BaseVariant.getNdkCompile()Lcom/android/build/gradle/tasks/NdkCompile;
        at com.uber.okbuck.core.model.android.AndroidAppTarget.<init>(AndroidAppTarget.java:52)
        at com.uber.okbuck.core.model.android.AndroidAppTarget.<init>(AndroidAppTarget.java:87)
        at com.uber.okbuck.core.model.base.TargetCache.lambda$getTargets$0(TargetCache.java:39)
        at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61)
        at com.uber.okbuck.core.model.base.TargetCache.getTargets(TargetCache.java:37)
        at com.uber.okbuck.generator.BuckFileGenerator.createRules(BuckFileGenerator.java:78)
```

Android Gradle Plugin 3.3.2 output:
```
WARNING: API 'variant.getNdkCompile()' is obsolete and has been replaced with 'variant.getNdkCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
```

okbuck version is 0.50.7

**Comment by carlonzo** [comment] 2020-07-01 10:14
duplicated of https://github.com/uber/okbuck/issues/840

**Comment by kageiit** [comment] 2020-07-01 16:53
duplicate of #840

**Closed by kageiit** 2020-07-01 16:53 UTC
