### ISSUE TITLE
Kotlin Dagger modules have issues with `internal` methods

### ISSUE THREAD

**Issue by NickFirmani** [uber/okbuck#835] opened 2019-04-10 02:11 UTC
When using the correct style for Kotlin Dagger modules, like the following 
```
@Module
abstract class OtherModule {

  @Module
  companion object {

    @Provides
    @JvmStatic
    @Singleton
    internal fun provideSomeObject(): SomeClass {
      // IRL you'd do some config here.
      return SomeClass()
    }
  }
}
```
Buck/Okbuck ends up with an error 

```
stderr: /com/nickfirmani/template/OtherModule_Companion_ProvideSomeObject$src_debugFactory.java:31: error: cannot find symbol
        instance.provideSomeObject$src_debug(),
                ^
  symbol:   method provideSomeObject$src_debug()
  location: variable instance of type com.nickfirmani.template.OtherModule.Companion
/com/nickfirmani/template/OtherModule_ProvideSomeObject$src_debugFactory.java:26: error: cannot find symbol
        OtherModule.provideSomeObject$src_debug(),
                   ^
  symbol:   method provideSomeObject$src_debug()
  location: class com.nickfirmani.template.OtherModule
Errors: 2. Warnings: 0.

    When running <javac>.
    When building rule //app:src_debug.
```

I'm not quite sure how to proceed, so I've created a sample recreation project, https://github.com/NickFirmani/android-template/commit/ddc402486d53103d98e15b5c3dd19251c950874b

Removing the internal keyword allows compilation to succeed

**Comment by kageiit** [comment] 2019-04-12 23:21
Seems like an update to buck would be needed. What kotlin version are you on? We fixed some issues with internal modifiers recently

**Comment by NickFirmani** [comment] 2019-04-13 00:48
The issue is reproducible on both Kotlin 1.3.21 and 1.3.30

**Comment by kageiit** [comment] 2019-04-15 12:40
cc @thalescm

**Comment by thalescm** [comment] 2019-04-15 15:03
The problem is about using `@JvmStatic` with `internal`. Did you check it this exact same code compiles with gradle? Last time I checked it didn't

**Comment by NickFirmani** [comment] 2019-04-16 00:47
No, the same code compiles just fine with gradle

**Comment by thalescm** [comment] 2019-04-16 06:58
Yeah, you might wanna open the issue on buck itself. I'm closing it here for now, but let us know if when it's fixed in buck, it continues to fail due to okbuck only

**Closed by thalescm** 2019-04-16 06:58 UTC
Labels: Upstream Buck Issue
