### ISSUE TITLE
res cannot coerce

### ISSUE THREAD

**Issue by Yuliya-Kaleda** [uber/okbuck#399] opened 2017-02-21 02:03 UTC
When running ./buckw targets, I get the following error message with okbuck 0.17.3.

`
BUILD FAILED: //MaterialShowcaseView:res_debug: parameter 'res': cannot coerce '{layout/showcase_content.xml=src/main/res/layout/showcase_content.xml}' to interface java.nio.file.Path
` 

 Buck version is 0a2f9ab183ae894d4446b057555b73b677c85a3a.  `./gradlew okbuck --stacktrace` outputs build successful.

**Comment by vanniktech** [comment] 2017-02-21 08:23
Dupe of #397 ?

**Comment by kageiit** [comment] 2017-02-21 18:03
What version of buck are you on?

**Comment by Yuliya-Kaleda** [comment] 2017-02-21 18:47
@kageiit Buck version is 0a2f9ab183ae894d4446b057555b73b677c85a3a

**Comment by kageiit** [comment] 2017-02-21 21:12
Can you update to the latest buck version? This is not an error from okbuck

**Comment by Yuliya-Kaleda** [comment] 2017-02-21 22:42
if `brew install buck` is the right command to update buck, I think there is an issue. I am getting .buckversion file generated with the same version (0a2f9ab183ae894d4446b057555b73b677c85a3a).

**Comment by kageiit** [comment] 2017-02-21 22:50
We do not recommend buck from brew. Always use `./buckw` that is the buck wrapper script provided by okbuck

https://github.com/uber/okbuck#buck-wrapper

**Comment by Yuliya-Kaleda** [comment] 2017-02-21 23:07
starting with a clean build and running  `./buckw targets`, I still see an old buck version. Do I miss a step to pull the latest buck version?

**Comment by kageiit** [comment] 2017-02-21 23:30
You need to add the latest buck sha to `.buckversion` file so that the wrapper can pull in the updates. `.buckversion` should be checked in to your repo and should point to whatever buckversion you want to use

**Comment by Yuliya-Kaleda** [comment] 2017-02-22 04:32
thanks a lot for a quick response. The latest buck version resolved the issue. Now dealing with a new one [#256](https://github.com/uber/okbuck/issues/256).

**Closed** 2017-02-22 05:51 UTC
Labels: Upstream Buck Issue
