### ISSUE TITLE
Unable to locate jar file from library module

### ISSUE THREAD

**Issue by kafji** [uber/okbuck#611] opened 2018-03-29 05:18 UTC
Let's say I have 2 gradle modules. One is an `app module` while the other is a `library module`. My `app module` depends on a jar file inside `library module`.

When I tried to build the project I got an error that says it can't found the rule for the jar.

Repro https://github.com/kafji/okbuckjarlibrepro
```
BUILD FAILED: The rule //.okbuck/cache:rxjava-2.1.12.rxjava-2.1.12.jar could not be found.
Please check the spelling and whether it exists in /home/user/myproject/.okbuck/cache/BUCK.

This error happened while trying to get dependency '//.okbuck/cache:rxjava-2.1.12.rxjava-2.1.12.jar' of target '//app:src_debug'
```

I tried to reproduce this issue in okbuck/app but it works as expected. https://github.com/kafji/okbuck/tree/jarlib

Am I missing something here, perhaps some configuration?

**Comment by kageiit** [comment] 2018-03-30 14:57
There is a bug here: https://github.com/kafji/okbuckjarlibrepro/blob/master/mylibrary/build.gradle#L29

The issue is you have no `libs` directory in your sample project with the jar checked in

**Comment by kafji** [comment] 2018-04-02 03:21
@kageiit sorry about that. I've updated the repro with the libs/jar added to git.

**Comment by kageiit** [comment] 2020-07-17 00:08
This should not longer be an issue with the latest okbuck. Please re-open if it happens on latest

**Closed by kageiit** 2020-07-17 00:08 UTC
Labels: question
