### ISSUE TITLE
Unable to find method (Gradle)

### ISSUE THREAD

**Issue by elsennov** [uber/okbuck#292] opened 2016-12-17 14:16 UTC
Hi i got this error when tried to use this library. Could you please help? Thanks!

```
Error:Unable to find method 'org.gradle.api.tasks.Sync.getInputs()Lorg/gradle/api/internal/TaskInputsInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by kageiit** [comment] 2016-12-18 01:43
Do you have same sample project? There is not much info to go on and there is no indication in the error stacktrace pointing to okbuck

**Comment by elsennov** [comment] 2016-12-18 04:23
Here it is my sample project https://github.com/elsennov/recipee @kageiit

**Comment by ljnalex** [comment] 2016-12-23 09:50
@kageiit I have the same problem，my as version is 2.2.2

**Comment by ljnalex** [comment] 2016-12-23 09:50
classpath 'com.android.tools.build:gradle:2.2.2'

**Comment by kageiit** [comment] 2016-12-23 17:47
@elsennov I am seeing this error on your sample project
```
* What went wrong:
A problem occurred configuring project ':app'.
> dokkakotlin.KotlinNullPointerException (no error message)
```

I think that maybe your root cause. Also, okbuck has no support for kotlin sources yet.

**Comment by alexfu** [comment] 2017-01-03 14:18
I ran into the same error in Android Studio (and I _**do not**_ use Kotlin in my app but I do use it for unit tests), but from the terminal I got the following error:

> Minimum supported Gradle version is 3.2. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in /Users/alexfu/Projects/work/everseat/android/gradle/wrapper/gradle-wrapper.properties to gradle-3.2-all.zip

I updated my gradle wrapper to 3.2 and subsequently had to update my `buildToolsVersion` to 25.0.0+ and it worked fine.

**Comment by kageiit** [comment] 2017-01-04 22:33
Closing this issue as okbuck does not support kotlin yet. @elsennov please comment if you see this issue on a non kotlin project and I will re-open this issue

**Closed by kageiit** 2017-01-04 22:33 UTC
Labels: Info Needed
