### ISSUE TITLE
Allow for resources to be generated via gradle (via resValue)

### ISSUE THREAD

**Issue by MichaelEvans** [uber/okbuck#225] opened 2016-11-02 17:35 UTC
It'd be great to support adding resources via gradle's mechanism like:

```
resValue "string", "key", "value"
```

**Comment by Piasy** [comment] 2016-11-03 01:04
I face the same problem, but if your string content is not dynamic, it could be put in xml.

**Comment by kageiit** [comment] 2016-11-04 04:47
@MichaelEvans can you use the suggested workaround and put the resources in xml instead?

This is the recommended approach for resources because `buckw` cannot infer dynamic resource values that change outside the `okbuck` gradle invocation. 

i.e if okbuck runs once from `buckw` and you change an environment variable (for example) that changes the res value, `buckw` has no way to know that it has to run okbuck again and it will lead to non reproducible builds. This is not a good practice for hermetic builds in general.

**Comment by kageiit** [comment] 2016-11-06 04:51
Closing due to suggested workaround. Please reach out of anything is missing and I can reopen

**Closed by kageiit** 2016-11-06 04:51 UTC

**Comment by friendoye** [comment] 2017-01-03 13:33
But what if I have several product flavors, that determine what resource values should be chosen?

As I see, if I change build.gradle, `okbuck` will remake BUCK file, so why can't we add resValue support?

**Comment by Piasy** [comment] 2017-01-03 15:25
flavor/variant could have a resource directory.

**Comment by kageiit** [comment] 2017-01-03 16:05
As @Piasy pointed out already, flavors can have their own resource directories and define values differently. Please use that mechanism instead
