### ISSUE TITLE
Issue with resources using okbuck

### ISSUE THREAD

**Issue by tmillettweather** [uber/okbuck#444] opened 2017-05-16 13:55 UTC
The following resources were not found when processing Pair(//app:res_googleDebug#resources-symlink-tree, buck-out/gen/app/res_googleDebug#resources-symlink-tree/res): 
RDotTxtEntry{idType=int, type=drawable, name=home_screen_gradient, idValue=0x00000000, parent=home_screen_gradient}

BUILD FAILED: //app:res_googleDebug failed with exit code 1:
generate_resource_ids

**Comment by kageiit** [comment] 2017-05-25 01:14
Possible duplicate of #318

**Comment by kageiit** [comment] 2017-06-26 04:58
Closing this as duplicate of #318 . See the workaround in https://github.com/uber/okbuck/issues/318#issuecomment-271396450

**Closed by kageiit** 2017-06-26 04:58 UTC
