### ISSUE TITLE
Compiler exception when using lambda in a unit test

### ISSUE THREAD

**Issue by konmik** [uber/okbuck#409] opened 2017-03-06 16:19 UTC
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

Reproduce:

1. Go to app/src/main/java/com.uber.okbuck.ExampleUnitTest
2. Add `Runnable runnable = () -> {};` line into `testAdd`
3. Run `./buckw test //app:test_devDebug`

Full error message:

```
An exception has occurred in the compiler (1.8.0_91). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

BUILD FAILED: //app:test_devDebug#testsjar failed with exit code 1:
javac_jar
stderr: An exception has occurred in the compiler (1.8.0_91). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```

**Comment by kageiit** [comment] 2017-03-06 16:41
Possible duplicate of https://github.com/uber/okbuck/issues/360#issuecomment-276014612

**Comment by kageiit** [comment] 2017-03-11 07:38
Closing this. Please comment back if the suggested solution from #360 did not work and I can re-open.

**Closed by kageiit** 2017-03-11 07:38 UTC

**Comment by konmik** [comment] 2017-03-13 12:11
Just updated from the main branch. Doesn't work still.

**Comment by kageiit** [comment] 2017-03-13 16:04
@konmik what did you try exactly? Did you add the real rt.jar from your system as a test dependency?

**Comment by konmik** [comment] 2017-03-13 20:47
Do I need to? What I do:

1. `git clone https://github.com/uber/okbuck.git`
2. Go to app/src/main/java/com.uber.okbuck.ExampleUnitTest
3. Add `Runnable runnable = () -> {};` line into testAdd
4. `./buckw test //app:test_devDebug`

That's all.

The entire log:

```
bash-3.2$ git clone https://github.com/uber/okbuck.git
Cloning into 'okbuck'...
remote: Counting objects: 9197, done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 9197 (delta 41), reused 0 (delta 0), pack-reused 9045
Receiving objects: 100% (9197/9197), 15.45 MiB | 2.35 MiB/s, done.
Resolving deltas: 100% (3934/3934), done.
Checking connectivity... done.

bash-3.2$ ./buckw test //app:test_devDebug
 NO PREVIOUS SUCCESSFUL OKBUCK RUN 
 RUNNING OKBUCK... 

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Start:buildSrc:clean UP-TO-DATE
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:buildSrc:processResources
:buildSrc:classes
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Cleaned up directory '/Users/kmikheev/git_tree/111/okbuck/buildSrc/build/classes/main'
Cleaned up directory '/Users/kmikheev/git_tree/111/okbuck/buildSrc/build/resources/main'
:setupOkbuck
:another-app:okbuck
:app:generateDemoDebugSqlDelightInterface
:app:generateDemoReleaseSqlDelightInterface
:app:generateDevDebugSqlDelightInterface
:app:generateDevReleaseSqlDelightInterface
:app:generateProdDebugSqlDelightInterface
:app:generateProdReleaseSqlDelightInterface
:app:okbuck
:dummylibrary:okbuck
:libraries:okbuck
:libraries:common:okbuck
:libraries:customLintLibrary:okbuck
:libraries:emptylibrary:okbuck
:libraries:groovylibrary:okbuck
:libraries:javalibrary:okbuck
:libraries:kotlinlibrary:okbuck
:libraries:lintErrorLibrary:okbuck
:libraries:parcelable:okbuck
:libraries:robolectric-base:okbuck
:okbuckClean
:okbuck

BUILD SUCCESSFUL

Total time: 23.05 secs

 PROCEEDING WITH BUCK 

Using watchman.
aidl E 43367 692763 aidl.cpp:537] refusing to generate code from aidl file defining parcelable

An exception has occurred in the compiler (1.8.0_91). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

BUILD FAILED: //app:test_devDebug#testsjar failed with exit code 1:
javac_jar
stderr: An exception has occurred in the compiler (1.8.0_91). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

[-] PROCESSING BUCK FILES...FINISHED 0.2s [100%] 🐳  New buck daemon
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 25.2s [100%] (194/195 JOBS, 193 UPDATED, 188 [96.4%] CACHE MISS)
    Details: http://localhost:56134/trace/70a6adb2-d522-4560-ac42-292cbf04cba2

bash-3.2$ 
```

**Comment by kageiit** [comment] 2017-03-13 21:00
@konmik Yes you do need to add the rt.jar ourself because that is not something we can ship with okbuck due to licensing restrictions from the jdk.

Please read https://github.com/uber/okbuck/issues/360#issuecomment-276014612 (the specific comment)

**Comment by konmik** [comment] 2017-03-15 09:05
The test passed! Horray! Can you make okbuck to automatically copy the file? You can't ship, but you can copy. Or make a link to it?

**Comment by kageiit** [comment] 2017-03-15 14:44
We cannot do that either really. We don't k ow what users do in there tests I.e use lambdas or not. We also do not know which jdk is being used for running the tests if multiple are installed on the user's machine. The provided workaround is reasonable and we will not be adding any more code from the okbuck side to make this happen automatically.

**Comment by kageiit** [comment] 2017-03-15 14:45
You can always copy the jar into your project workspace and check it in. That way the configuration is one time and can be used across members of your team.

**Comment by konmik** [comment] 2017-03-15 16:05
```
BUILD FAILED: //.okbuck/cache:rt.rt.jar#dex failed with exit code 1:
dx

Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
 ```

while starting instrumentation tests

can we have the rt.jar workaround used only for unit-tests somehow?

**Comment by kageiit** [comment] 2017-03-15 17:14
yes just put it under `testCompile` . It should not be needed for `androidTestCompile`. check your gradle config to make sure you are not pulling it in transitively

**Comment by konmik** [comment] 2017-03-16 10:05
It is already `testCompile files('libs_temp/rt.jar')`, I even placed it into a separate library to not interfere with other inclusions

**Comment by kageiit** [comment] 2017-03-16 15:32
Check if your android-eats impulse is extending your test compile configuration. If so, you may want to remove that or use a dependency exclusion rule to filter out the RT.jar

Can't say anything more unless I have insight into what your configuration looks like in full

**Comment by konmik** [comment] 2017-03-17 21:12
This is reproducible on your configuration.

Just add `rt.jar` and try running the instrumentation test.
