### ISSUE TITLE
Changes in AndroidManifest.xml not detected

### ISSUE THREAD

**Issue by marcherdiego** [uber/okbuck#525] opened 2017-09-21 19:03 UTC
I've added two activities to the manifest file of a module. This module is used in the main module, I can see the two new activities in the merged manifest in Android Studio, but if I simply run okbuck, the change seems not to be applied. 
I had to clean build with buck again to see the change. Any hint?

**Comment by kageiit** [comment] 2017-09-21 21:09
Okbuck does not generate merged manifests from libraries. Buck does

You need to build with buck to see the changes

**Comment by marcherdiego** [comment] 2017-09-22 14:18
@kageiit What do you mean? 
Shouldn't it be simply `./buckw build _target_` and then `./buckw install --run _target_`? Am I missing something?

Thanks!

**Comment by marcherdiego** [comment] 2017-09-29 14:49
Hi @kageiit, can you please add some additional information about this? I really don't understand the reason why :( 

Thanks!

**Comment by kageiit** [comment] 2018-01-26 14:42
Needs more info to repro. Please comment if the issue is still happening on latest okbuck version. Closing due to inactivity for now

**Closed by kageiit** 2018-01-26 14:42 UTC
