### ISSUE TITLE
java.lang.RuntimeException: Failed to backport class: com/myapp/android/rx/RxLogger

### ISSUE THREAD

**Issue by vanniktech** [uber/okbuck#335] opened 2017-01-16 15:30 UTC
When running `buckw test`, I get the following error message with okbuck 0.14.3:

```
Retrolambda 2.3.0
Bytecode version: 51 (Java 7)
Default methods:  false
Input directory:  buck-out/bin/app/lib__src_debug__classes
Output directory: buck-out/bin/app/lib__src_debug__classes
Classpath:        [buck-out/bin/app/lib__src_debug__classes]
Included files:   all
Agent enabled:    false
Error! Failed to run Retrolambda
java.lang.RuntimeException: Failed to backport class: com/myapp/android/rx/RxLogger
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:128)
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:107)
  at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:47)
  at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:77)
  at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.RuntimeException: Failed to backport lambda or method reference: com/myapp/android/rx/RxLogger.lambda$static$0(Ljava/lang/Throwable;)V (6)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
  at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:171)
  at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:160)
  at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1452)
  at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
  at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
  at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
  at net.orfjackal.retrolambda.Transformers.lambda$transform$5(Transformers.java:107)
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:124)
  ... 4 more
Caused by: java.lang.TypeNotPresentException: Type io.reactivex.functions.Consumer not present
  at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
  at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:63)
  at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
  at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
  at net.orfjackal.retrolambda.lambdas.Types.toMethodType(Types.java:33)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:104)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
  ... 12 more
Caused by: java.lang.ClassNotFoundException: io.reactivex.functions.Consumer
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
  at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
  ... 18 more


Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true

Retrolambda 2.3.0
Bytecode version: 51 (Java 7)
Default methods:  false
Input directory:  buck-out/bin/app/lib__src_release__classes
Output directory: buck-out/bin/app/lib__src_release__classes
Classpath:        [buck-out/bin/app/lib__src_release__classes]
Included files:   all
Agent enabled:    false
Error! Failed to run Retrolambda
java.lang.RuntimeException: Failed to backport class: com/myapp/android/rx/RxLogger
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:128)
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:107)
  at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:47)
  at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:77)
  at net.orfjackal.retrolambda.Main.main(Main.java:26)
Caused by: java.lang.RuntimeException: Failed to backport lambda or method reference: com/myapp/android/rx/RxLogger.lambda$static$0(Ljava/lang/Throwable;)V (6)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:42)
  at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.backportLambda(BackportLambdaInvocations.java:171)
  at net.orfjackal.retrolambda.lambdas.BackportLambdaInvocations$InvokeDynamicInsnConverter.visitInvokeDynamicInsn(BackportLambdaInvocations.java:160)
  at net.orfjackal.retrolambda.asm.ClassReader.readCode(ClassReader.java:1452)
  at net.orfjackal.retrolambda.asm.ClassReader.readMethod(ClassReader.java:1017)
  at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:693)
  at net.orfjackal.retrolambda.asm.ClassReader.accept(ClassReader.java:506)
  at net.orfjackal.retrolambda.Transformers.lambda$transform$5(Transformers.java:107)
  at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:124)
  ... 4 more
Caused by: java.lang.TypeNotPresentException: Type io.reactivex.functions.Consumer not present
  at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
  at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:63)
  at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
  at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
  at net.orfjackal.retrolambda.lambdas.Types.toMethodType(Types.java:33)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.callBootstrapMethod(LambdaReifier.java:104)
  at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:37)
  ... 12 more
Caused by: java.lang.ClassNotFoundException: io.reactivex.functions.Consumer
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at net.orfjackal.retrolambda.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:27)
  at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
  ... 18 more

Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true

BUILD FAILED: //app:src_debug failed with exit code 1:
bash
stderr: Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
```

RxLogger looks like this:

```java
public final class RxLogger {
  private static final Consumer<Throwable> LOG = throwable -> {
    if (BuildConfig.DEBUG) {
      Exceptions.sneakyRethrow(throwable);
    } else {
      Timber.w(throwable);
    }
  };

  public static Consumer<Throwable> log() {
    return LOG;
  }

  private RxLogger() {
    throw new AssertionError("No instances.");
  }
}
```

**Comment by vanniktech** [comment] 2017-01-17 10:02
Lint also seems to have troubles with that file:

```
Failed converting ECJ parse tree to Lombok for file /path/app/src/main/java/com/myapp/android/rx/RxLogger.java
java.lang.UnsupportedOperationException: Unknown ASTNode child: LambdaExpression
  at lombok.ast.ecj.EcjTreeVisitor.visitOther(EcjTreeVisitor.java:368)
  at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:364)
  at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
  at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
  at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:229)
  at lombok.ast.ecj.EcjTreeConverter.createVariableDefinition(EcjTreeConverter.java:352)
  at lombok.ast.ecj.EcjTreeConverter.toVariableDefinition(EcjTreeConverter.java:305)
  at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:280)
  at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
  at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
  at lombok.ast.ecj.EcjTreeConverter$2.createNormalTypeBody(EcjTreeConverter.java:563)
  at lombok.ast.ecj.EcjTreeConverter$2.visitTypeDeclaration(EcjTreeConverter.java:486)
  at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:48)
  at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
  at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:236)
  at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:282)
  at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:252)
  at lombok.ast.ecj.EcjTreeConverter.access$100(EcjTreeConverter.java:141)
  at lombok.ast.ecj.EcjTreeConverter$2.visitCompilationUnitDeclaration(EcjTreeConverter.java:441)
  at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:264)
  at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:295)
  at com.android.tools.lint.EcjParser.parseJava(EcjParser.java:831)
  at com.android.tools.lint.client.api.JavaVisitor.visitFile(JavaVisitor.java:235)
  at com.android.tools.lint.client.api.LintDriver.visitJavaFiles(LintDriver.java:1736)
  at com.android.tools.lint.client.api.LintDriver.checkJava(LintDriver.java:1654)
  at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.java:1185)
  at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.java:1039)
  at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:552)
  at com.android.tools.lint.client.api.LintDriver.analyze(LintDriver.java:483)
  at com.android.tools.lint.LintCliClient.run(LintCliClient.java:143)
  at com.android.build.gradle.internal.LintGradleClient.run(LintGradleClient.java:153)
  at com.android.build.gradle.tasks.Lint.runLint(Lint.java:340)
  at com.android.build.gradle.tasks.Lint.lintSingleVariant(Lint.java:307)
  at com.android.build.gradle.tasks.Lint.lint(Lint.java:119)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
  at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
  at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
  at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
  at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
  at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
  at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
  at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
  at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
  at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
  at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
  at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
  at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
  at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
  at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
  at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
  at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
  at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
  at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
  at org.gradle.util.Swapper.swap(Swapper.java:38)
  at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
  at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
  at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
  at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
  at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
  at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by kageiit** [comment] 2017-01-18 02:22
This seems like a missing classpath dependency on retrolambda. Does the class work in gradle?

**Comment by vanniktech** [comment] 2017-01-18 08:19
Yup everything works there.

**Comment by kageiit** [comment] 2017-01-18 17:47
@vanniktech Can you drop this class in your okbuck playground sample project with required dependencies so we can analyze the root cause?

Thanks

**Comment by vanniktech** [comment] 2017-01-18 21:28
Unfortunately just putting it in with the dependencies does not trigger the issue. I'll try again is there for now any other information I can give you?

**Comment by kageiit** [comment] 2017-01-18 21:50
Some way to repro would be useful. The folks at airbnb have been able to use retrolambda with no issues for months now using okbuck+buck, so its very hard to tell what the issue is unless there are clear repro steps.

**Comment by vanniktech** [comment] 2017-01-28 11:42
Just to give it an update. On my Mac I still have this issue although on my Linux machine at home I am not encountering this issue, so I'm thinking that there's something wrong with my Mac. I also tried building the same project already on a few machines from coworkers and they didn't face it either.

**Comment by kageiit** [comment] 2017-01-28 18:14
Please post back the cause if you find one. Closing this as it is not occuring for everyone

**Closed by kageiit** 2017-01-28 18:14 UTC
Labels: Info Needed

**Comment by vanniktech** [comment] 2017-01-29 13:35
I reran this one again with verbosity turned on and found another stacktrace:

```
[2017-01-29 14:33:49.032][debug][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:449][com.facebook.buck.step.DefaultStepRunner] StepFinished(bash)

[2017-01-29 14:33:49.035][debug][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:428][com.facebook.buck.command.Build] Got an exception during the build.
com.facebook.buck.step.StepFailedException: //app:src_debug failed with exit code 1:
(cd /Users/nik/tmp/myproject && bash -c '(read CLASSES_DIR && java -Dretrolambda.inputDir="${CLASSES_DIR}" -Dretrolambda.classpath="${COMPILATION_BOOTCLASSPATH}":"${COMPILATION_CLASSPATH}":"${CLASSES_DIR}" -jar .okbuck/cache/retrolambda/retrolambda-2.3.0.jar) <<< buck-out/bin/app/lib__src_debug__classes')
stderr:
  at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:63)
  at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:62)
  at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1359)
  at com.facebook.buck.rules.CachingBuildEngine.lambda$10(CachingBuildEngine.java:340)
  at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
  at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
  at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
  at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
  at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)


BUILD FAILED: //app:src_debug failed with exit code 1:
(cd /Users/nik/tmp/myproject && bash -c '(read CLASSES_DIR && java -Dretrolambda.inputDir="${CLASSES_DIR}" -Dretrolambda.classpath="${COMPILATION_BOOTCLASSPATH}":"${COMPILATION_CLASSPATH}":"${CLASSES_DIR}" -jar .okbuck/cache/retrolambda/retrolambda-2.3.0.jar) <<< buck-out/bin/app/lib__src_debug__classes')
stderr:
[2017-01-29 14:33:49.036][warn ][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:440][com.facebook.buck.event.listener.LoggingBuildListener] BUILD FAILED: //app:src_debug failed with exit code 1:
(cd /Users/nik/tmp/myproject && bash -c '(read CLASSES_DIR && java -Dretrolambda.inputDir="${CLASSES_DIR}" -Dretrolambda.classpath="${COMPILATION_BOOTCLASSPATH}":"${COMPILATION_CLASSPATH}":"${CLASSES_DIR}" -jar .okbuck/cache/retrolambda/retrolambda-2.3.0.jar) <<< buck-out/bin/app/lib__src_debug__classes')
stderr:

[-] BUILDING...FINISHED 7.0s [100%]
[2017-01-29 14:33:49.037][info ][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:428][com.facebook.buck.cli.Main] Awaiting termination of HTTP Write executor service. Waiting for all jobs to complete, or up to maximum of 1800 seconds...

[2017-01-29 14:33:49.037][info ][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:440][com.facebook.buck.event.listener.LoggingBuildListener] Build finished at 2017-01-29 14:33:49.035

[2017-01-29 14:33:49.037][info ][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:428][com.facebook.buck.cli.Main] Awaiting termination of CounterAggregatorExecutor executor service. Waiting for all jobs to complete, or up to maximum of 20 seconds...

[2017-01-29 14:33:49.037][debug][command:f05651c4-934d-4fe6-9d3f-c95b2e7891d4][tid:439][com.facebook.buck.util.perf.ProcessTracker] shutDown
```

Can you make any sense out of this one?

**Comment by vanniktech** [comment] 2017-01-30 08:54
Seems like upgrading to `0.16.0` (`0.16.3` also works in this regard) and buckversion `3319cd6ce5c0126fea859932cc5c2494e95b63b9` fixes this issue.
