### ISSUE TITLE
Failing -- Okbuck(0.28.9) is failing with android plugin 3.0.0-beta6

### ISSUE THREAD

**Issue by krishnaChaitanyaAripaka** [uber/okbuck#534] opened 2017-10-13 06:44 UTC
Hi,
I tried integrating okbuck in my app with following configurations and I have observed strange behaviour with okbuck. It does not work for the below configuration

Failure : Gradle 4.1, Android Plugin 3.0.0-beta6, okbuck (from 0.24.0)

Success : Gradle 4.1, Android Plugin 2.3.3, okbuck (all versions)
Success : Gradle 4.1, Android Plugin 3.0.0-beta6, okbuck (till 0.23.3)

What went wrong:
Execution failed for task ':app:okbuck'.
Resolving configuration 'debugCompile' directly is not allowed

**Comment by kageiit** [comment] 2017-10-13 06:46
This is expected. Agp 3.x support is not yet merged

**Comment by krishnaChaitanyaAripaka** [comment] 2017-10-13 07:21
Thanks for the update. When can we expect support ?

Android Plugin 3.0.0-beta7 with okbuck 0.23.0 is failing with following error

What went wrong:
Execution failed for task ':app:okbuck'.
> Resolving configuration 'annotationProcessor' directly is not allowed

So which version of okbuck can we use as of now ?

**Comment by kageiit** [comment] 2017-10-13 09:00
Okbuck does not support any version of 3.x . 

Please follow https://github.com/uber/okbuck/milestones for updates

**Comment by kageiit** [comment] 2017-10-13 09:00
Duplicate of #502

**Closed by kageiit** 2017-10-13 09:00 UTC
